- name: Setup Database Server

  hosts: dbserver
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
    - name: ping
      ping:
  roles:
    - python
    - mysql_db

- name: Setup Web Servers
  hosts: webservers
  become: yes
  become_method: sudo
  connection: ssh
  roles:
    - python
    - flask_web
